In [43]:
import numpy as np
import plotly.graph_objects as go

In [44]:
corrected_wall_90_deg = [[ 2.35380325e-02,  2.56796739e-05, -1.55391439e-03,  0.00000000e+00,
   2.56796739e-05,  7.93246145e-05, -9.68469903e-05,  0.00000000e+00,
  -1.55391439e-03, -9.68469903e-05,  2.97766905e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.85130458e-02,  3.79618187e-03,  3.80248204e-03,  0.00000000e+00,
   3.79618187e-03,  1.22737102e-02,  4.47363686e-03,  0.00000000e+00,
   3.80248204e-03,  4.47363686e-03,  5.21464413e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.71527432e-02,  2.61628065e-05, -6.62302459e-03,  0.00000000e+00,
   2.61628065e-05,  8.68357747e-05, -4.54186142e-04,  0.00000000e+00,
  -6.62302459e-03, -4.54186142e-04,  2.82598697e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.22893499e-02,  1.71765932e-04,  6.50534581e-04,  0.00000000e+00,
   1.71765932e-04,  7.11450266e-05,  4.82931173e-05,  0.00000000e+00,
   6.50534581e-04,  4.82931173e-05,  2.37708241e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.58266272e-02, -7.73367239e-03, -1.10107306e-02,  0.00000000e+00,
  -7.73367239e-03,  8.33728630e-03,  7.75921158e-03,  0.00000000e+00,
  -1.10107306e-02,  7.75921158e-03,  2.16463469e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.44778034e-02,  4.67989687e-03,  6.73519634e-03,  0.00000000e+00,
   4.67989687e-03,  1.04556577e-02,  1.03074871e-02,  0.00000000e+00,
   6.73519634e-03,  1.03074871e-02,  2.63823643e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.64123867e-02,  9.22380932e-05,  2.61585531e-03,  0.00000000e+00,
   9.22380932e-05,  1.00426849e-04,  1.42747958e-04,  0.00000000e+00,
   2.61585531e-03,  1.42747958e-04,  4.94720638e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.45311910e-02, -1.22662634e-04, -3.53920856e-04,  0.00000000e+00,
  -1.22662634e-04,  1.03686289e-04,  1.59199524e-04,  0.00000000e+00,
  -3.53920856e-04,  1.59199524e-04,  1.90559644e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.83660144e-02,  4.12118767e-04,  5.71288774e-03,  0.00000000e+00,
   4.12118767e-04,  8.86243579e-05,  1.43176367e-04,  0.00000000e+00,
   5.71288774e-03,  1.43176367e-04,  2.96718441e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.12679617e-02, -1.18517154e-03, -1.12233439e-03,  0.00000000e+00,
  -1.18517154e-03,  1.23373009e-02,  4.91475314e-03,  0.00000000e+00,
  -1.12233439e-03,  4.91475314e-03,  5.55179827e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.51193885e-02,  4.29748980e-05,  2.79704737e-03,  0.00000000e+00,
   4.29748980e-05,  1.14614813e-04,  8.70092626e-05,  0.00000000e+00,
   2.79704737e-03,  8.70092626e-05,  1.72859635e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.22982818e-02,  4.03240643e-04, -1.74507510e-03,  0.00000000e+00,
   4.03240643e-04,  8.67768904e-05,  2.12337545e-05,  0.00000000e+00,
  -1.74507510e-03,  2.12337545e-05,  2.75492482e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.36906391e-02,  1.90551963e-03, -1.02559815e-03,  0.00000000e+00,
   1.90551963e-03,  3.46489460e-03,  3.96616012e-03,  0.00000000e+00,
  -1.02559815e-03,  3.96616012e-03,  1.45427408e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 6.04543760e-02,  1.80985749e-04, -4.16218443e-03,  0.00000000e+00,
   1.80985749e-04,  8.61975786e-05,  2.41697635e-05,  0.00000000e+00,
  -4.16218443e-03,  2.41697635e-05,  1.59407556e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.93548496e-02,  1.23767837e-04,  2.48005311e-03,  0.00000000e+00,
   1.23767837e-04,  1.14401570e-04,  1.18247437e-04,  0.00000000e+00,
   2.48005311e-03,  1.18247437e-04,  1.09675657e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.61903331e-02, -2.08320009e-04,  1.31191616e-03,  0.00000000e+00,
  -2.08320009e-04,  1.19774209e-04,  4.32622801e-05,  0.00000000e+00,
   1.31191616e-03,  4.32622801e-05,  1.63747258e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.66079472e-02,  2.98185405e-05,  1.36768939e-02,  0.00000000e+00,
   2.98185405e-05,  8.86341659e-05,  1.76791262e-04,  0.00000000e+00,
   1.36768939e-02,  1.76791262e-04,  2.51187608e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.78350655e-02,  1.35843846e-04, -5.25157992e-03,  0.00000000e+00,
   1.35843846e-04,  1.05994463e-04, -1.38460993e-04,  0.00000000e+00,
  -5.25157992e-03, -1.38460993e-04,  4.37787175e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.66501140e-02, -4.80894923e-05,  2.97896238e-03,  0.00000000e+00,
  -4.80894923e-05,  9.25319328e-05,  2.66197632e-04,  0.00000000e+00,
   2.97896238e-03,  2.66197632e-04,  2.98621282e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.11423638e-02, -3.53643009e-05,  3.65150510e-03,  0.00000000e+00,
  -3.53643009e-05,  1.05506952e-04,  6.49500653e-05,  0.00000000e+00,
   3.65150510e-03,  6.49500653e-05,  3.93464006e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.99406888e-02, -5.14372659e-05,  3.31416610e-03,  0.00000000e+00,
  -5.14372659e-05,  9.77270975e-05, -8.14469313e-05,  0.00000000e+00,
   3.31416610e-03, -8.14469313e-05,  2.52028052e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.00411864e-02, -1.49512244e-03, -5.65532828e-04,  0.00000000e+00,
  -1.49512244e-03,  1.26986299e-02,  5.25538391e-03,  0.00000000e+00,
  -5.65532828e-04,  5.25538391e-03,  5.46529982e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.35884078e-02,  5.61239285e-05, -1.07544409e-02,  0.00000000e+00,
   5.61239285e-05,  1.14555136e-04,  1.07443069e-04,  0.00000000e+00,
  -1.07544409e-02,  1.07443069e-04,  4.24710736e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.60171371e-02,  1.63581455e-03,  6.22076914e-03,  0.00000000e+00,
   1.63581455e-03,  1.13340430e-02,  1.12685617e-02,  0.00000000e+00,
   6.22076914e-03,  1.12685617e-02,  2.76544057e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.18844574e-02, -1.28695856e-05,  5.81483298e-04,  0.00000000e+00,
  -1.28695856e-05,  1.02510647e-04, -3.52884264e-04,  0.00000000e+00,
   5.81483298e-04, -3.52884264e-04,  3.37835923e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.52647884e-02,  1.37471972e-04, -1.68365578e-03,  0.00000000e+00,
   1.37471972e-04,  8.30001736e-05,  2.47168035e-04,  0.00000000e+00,
  -1.68365578e-03,  2.47168035e-04,  1.98103152e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.46431418e-02, -1.08737659e-05,  5.09889517e-03,  0.00000000e+00,
  -1.08737659e-05,  8.87902206e-05, -2.83395377e-04,  0.00000000e+00,
   5.09889517e-03, -2.83395377e-04,  2.61398535e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.94205586e-02,  5.71040327e-05, -2.51929695e-03,  0.00000000e+00,
   5.71040327e-05,  1.00250014e-04,  2.15369684e-04,  0.00000000e+00,
  -2.51929695e-03,  2.15369684e-04,  2.09402591e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.85162835e-02,  1.77725829e-04,  1.49921456e-03,  0.00000000e+00,
   1.77725829e-04,  1.07055901e-04, -2.58263262e-05,  0.00000000e+00,
   1.49921456e-03, -2.58263262e-05,  7.40349432e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.20222175e-02, -1.54068519e-04, -5.98541787e-03,  0.00000000e+00,
  -1.54068519e-04,  1.43113153e-04, -2.71093915e-04,  0.00000000e+00,
  -5.98541787e-03, -2.71093915e-04,  2.98568048e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.33482860e-02,  4.45551844e-03,  1.68880390e-03,  0.00000000e+00,
   4.45551844e-03,  1.27184391e-02,  4.95409546e-03,  0.00000000e+00,
   1.68880390e-03,  4.95409546e-03,  5.91196911e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10]]


default_wall_90_deg = [[ 1.07669821e-02,  1.79623638e-03,  7.77633744e-04,  0.00000000e+00,
   1.79623638e-03,  4.79415001e-04,  8.03695351e-04,  0.00000000e+00,
   7.77633744e-04,  8.03695351e-04,  2.44867206e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.47997914e-02,  2.12937291e-03, -3.22822621e-03,  0.00000000e+00,
   2.12937291e-03,  4.35533060e-04, -5.83958172e-04,  0.00000000e+00,
  -3.22822621e-03, -5.83958172e-04,  2.84123104e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.86484344e-02,  3.03580170e-03,  6.65136031e-04,  0.00000000e+00,
   3.03580170e-03,  1.15253986e-03,  1.92900433e-03,  0.00000000e+00,
   6.65136031e-04,  1.92900433e-03,  2.19173394e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.26140134e-02,  3.30134016e-03,  2.22526694e-04,  0.00000000e+00,
   3.30134016e-03,  5.89522766e-04,  2.10435974e-04,  0.00000000e+00,
   2.22526694e-04,  2.10435974e-04,  2.23097671e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 7.49261165e-03,  9.91852721e-04,  5.14339004e-03,  0.00000000e+00,
   9.91852721e-04,  2.33103579e-04,  2.74878519e-04,  0.00000000e+00,
   5.14339004e-03,  2.74878519e-04,  5.54314256e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.01446470e-02,  3.05569964e-03, -5.80407563e-04,  0.00000000e+00,
   3.05569964e-03,  5.52548445e-04, -3.76918906e-04,  0.00000000e+00,
  -5.80407563e-04, -3.76918906e-04,  1.53966816e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.12877619e-02,  1.60414004e-03,  4.40076040e-03,  0.00000000e+00,
   1.60414004e-03,  3.15581972e-04,  5.32000093e-04,  0.00000000e+00,
   4.40076040e-03,  5.32000093e-04,  2.22240575e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.70570868e-02,  4.20097355e-03, -2.68629449e-03,  0.00000000e+00,
   4.20097355e-03,  1.45865197e-03,  1.47053378e-03,  0.00000000e+00,
  -2.68629449e-03,  1.47053378e-03,  1.83000807e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.99359655e-02,  2.60200165e-03, -4.97001223e-03,  0.00000000e+00,
   2.60200165e-03,  4.71362117e-04, -8.60694970e-04,  0.00000000e+00,
  -4.97001223e-03, -8.60694970e-04,  2.46627219e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.25900225e-02,  3.13226203e-03, -2.26744451e-03,  0.00000000e+00,
   3.13226203e-03,  5.64063434e-04, -4.52106120e-04,  0.00000000e+00,
  -2.26744451e-03, -4.52106120e-04,  2.57502608e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 8.28231871e-03,  8.41322879e-04,  5.45947114e-03,  0.00000000e+00,
   8.41322879e-04,  1.74340690e-04,  3.76521726e-04,  0.00000000e+00,
   5.45947114e-03,  3.76521726e-04,  1.66622866e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.73647031e-02,  2.42869323e-03, -5.65089693e-04,  0.00000000e+00,
   2.42869323e-03,  4.33516194e-04,  6.52648014e-05,  0.00000000e+00,
  -5.65089693e-04,  6.52648014e-05,  3.50584835e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.28222965e-02,  1.93377491e-03,  7.17996666e-03,  0.00000000e+00,
   1.93377491e-03,  3.90792295e-04,  7.69561739e-04,  0.00000000e+00,
   7.17996666e-03,  7.69561739e-04,  2.60754786e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.56822428e-02,  2.24183383e-03,  8.01488291e-03,  0.00000000e+00,
   2.24183383e-03,  4.27440566e-04,  1.01463567e-03,  0.00000000e+00,
   8.01488291e-03,  1.01463567e-03,  1.65366251e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.08030958e-02,  2.97113182e-03,  4.15995298e-03,  0.00000000e+00,
   2.97113182e-03,  5.18939167e-04,  5.55224309e-04,  0.00000000e+00,
   4.15995298e-03,  5.55224309e-04,  2.24058665e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.60994288e-02,  2.50966521e-03, -1.28318998e-03,  0.00000000e+00,
   2.50966521e-03,  4.91620856e-04, -3.52813455e-04,  0.00000000e+00,
  -1.28318998e-03, -3.52813455e-04,  1.83129702e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.97679326e-02,  2.81499256e-03,  9.79471300e-03,  0.00000000e+00,
   2.81499256e-03,  4.93046362e-04,  1.54649757e-03,  0.00000000e+00,
   9.79471300e-03,  1.54649757e-03,  1.75762717e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.65541896e-02,  3.52183962e-03, -8.74864403e-04,  0.00000000e+00,
   3.52183962e-03,  1.08112383e-03,  7.01659708e-04,  0.00000000e+00,
  -8.74864403e-04,  7.01659708e-04,  5.95934084e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.99022554e-02,  2.65634246e-03,  5.88014582e-03,  0.00000000e+00,
   2.65634246e-03,  4.57280141e-04,  5.99249615e-04,  0.00000000e+00,
   5.88014582e-03,  5.99249615e-04,  1.30147673e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.75744237e-02,  3.93684860e-03, -3.50080780e-03,  0.00000000e+00,
   3.93684860e-03,  6.65900123e-04, -3.81996681e-04,  0.00000000e+00,
  -3.50080780e-03, -3.81996681e-04,  1.21665457e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.31410761e-02,  2.07278621e-03, -2.07851292e-03,  0.00000000e+00,
   2.07278621e-03,  4.41498822e-04, -2.14042564e-04,  0.00000000e+00,
  -2.07851292e-03, -2.14042564e-04,  1.47257438e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 8.48473050e-03,  1.05098821e-03, -7.04949209e-03,  0.00000000e+00,
   1.05098821e-03,  3.61727580e-04, -7.07917206e-04,  0.00000000e+00,
  -7.04949209e-03, -7.07917206e-04,  2.05233470e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.60276029e-02,  5.47068752e-03,  3.82525730e-03,  0.00000000e+00,
   5.47068752e-03,  9.30102426e-04,  5.98969113e-04,  0.00000000e+00,
   3.82525730e-03,  5.98969113e-04,  1.05732717e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.64344944e-02,  2.60609924e-03,  5.14831254e-03,  0.00000000e+00,
   2.60609924e-03,  4.92067891e-04,  9.11919284e-04,  0.00000000e+00,
   5.14831254e-03,  9.11919284e-04,  1.76820457e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.16645282e-02,  2.93117599e-03, -1.71478372e-03,  0.00000000e+00,
   2.93117599e-03,  5.05653734e-04,  3.45462263e-06,  0.00000000e+00,
  -1.71478372e-03,  3.45462263e-06,  7.72167603e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.29227857e-02,  4.71100584e-03,  3.05263163e-03,  0.00000000e+00,
   4.71100584e-03,  8.16438813e-04,  5.78499108e-04,  0.00000000e+00,
   3.05263163e-03,  5.78499108e-04,  6.53947610e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.05027293e-02,  3.30256764e-03, -8.97383317e-03,  0.00000000e+00,
   3.30256764e-03,  6.46684901e-04, -1.27205637e-03,  0.00000000e+00,
  -8.97383317e-03, -1.27205637e-03,  1.47796925e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.55942980e-02,  2.45312136e-03,  3.03190248e-03,  0.00000000e+00,
   2.45312136e-03,  4.59410629e-04,  5.73838013e-04,  0.00000000e+00,
   3.03190248e-03,  5.73838013e-04,  1.53992446e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.58023220e-02,  2.44066748e-03,  1.38510586e-04, -5.73018318e-16,
   2.44066748e-03,  4.48929757e-04,  1.97258822e-04,  1.44400618e-14,
   1.38510586e-04,  1.97258822e-04,  3.34861572e-03,  5.15716476e-15,
  -5.73018318e-16,  1.44400618e-14,  5.15716476e-15,  1.00000890e-10],
 [ 5.76962112e-03,  9.90430242e-04, -2.13650428e-03,  0.00000000e+00,
   9.90430242e-04,  2.84576701e-04, -3.86486150e-04,  0.00000000e+00,
  -2.13650428e-03, -3.86486150e-04,  2.07880829e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.75688919e-02,  2.09840527e-03, -2.14629853e-03,  0.00000000e+00,
   2.09840527e-03,  1.38587318e-03,  8.45941599e-04,  0.00000000e+00,
  -2.14629853e-03,  8.45941599e-04,  4.12352011e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.81760341e-02,  2.56576249e-03,  3.27454857e-03,  0.00000000e+00,
   2.56576249e-03,  4.47384344e-04,  5.33897139e-04,  0.00000000e+00,
   3.27454857e-03,  5.33897139e-04,  1.20430719e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.70140190e-02,  3.54310195e-03, -5.38929505e-03,  0.00000000e+00,
   3.54310195e-03,  5.59814216e-04, -5.43498492e-04,  0.00000000e+00,
  -5.38929505e-03, -5.43498492e-04,  8.75218399e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.41857583e-02,  1.88784138e-03,  3.68256937e-03,  0.00000000e+00,
   1.88784138e-03,  3.31649993e-04,  2.73960963e-04,  0.00000000e+00,
   3.68256937e-03,  2.73960963e-04,  1.54288542e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.84875764e-02,  2.87934369e-03,  5.43468399e-04,  0.00000000e+00,
   2.87934369e-03,  9.24833934e-04,  8.07089906e-04,  0.00000000e+00,
   5.43468399e-04,  8.07089906e-04,  3.49660683e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10]]

In [45]:
default_wall_cov_2 = [[ 1.55260535e-02,  2.19014147e-03, -3.13255982e-03,  0.00000000e+00,
   2.19014147e-03,  4.01587517e-04, -1.81172160e-04,  0.00000000e+00,
  -3.13255982e-03, -1.81172160e-04,  2.38000508e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.68994477e-02,  3.91697558e-03,  3.75225442e-03,  0.00000000e+00,
   3.91697558e-03,  6.58864970e-04,  4.85764089e-04,  0.00000000e+00,
   3.75225442e-03,  4.85764089e-04,  1.57701597e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.05785830e-02,  1.71707035e-03, -3.39485821e-03,  0.00000000e+00,
   1.71707035e-03,  3.92329239e-04, -5.50291850e-04,  0.00000000e+00,
  -3.39485821e-03, -5.50291850e-04,  1.84747037e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.75559670e-02,  2.61166552e-03,  1.51436776e-03,  0.00000000e+00,
   2.61166552e-03,  5.20438596e-04,  1.55882692e-04,  0.00000000e+00,
   1.51436776e-03,  1.55882692e-04,  7.60809565e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.61082596e-02,  2.24505342e-03, -2.35196133e-03,  0.00000000e+00,
   2.24505342e-03,  4.12019843e-04, -3.81542020e-04,  0.00000000e+00,
  -2.35196133e-03, -3.81542020e-04,  2.84102727e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.86826475e-02,  3.86841944e-03,  1.66708475e-03,  0.00000000e+00,
   3.86841944e-03,  1.51506846e-03,  1.36926130e-03,  0.00000000e+00,
   1.66708475e-03,  1.36926130e-03,  7.90141523e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.98374819e-02,  2.52842554e-03,  7.32050696e-03,  0.00000000e+00,
   2.52842554e-03,  3.79434961e-04,  7.64692028e-04,  0.00000000e+00,
   7.32050696e-03,  7.64692028e-04,  2.51349919e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.55819634e-02,  3.91926523e-03,  3.82781669e-04,  0.00000000e+00,
   3.91926523e-03,  7.23495090e-04,  2.89446325e-05,  0.00000000e+00,
   3.82781669e-04,  2.89446325e-05,  1.93348266e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.09750004e-02, -6.77310571e-04, -6.09591836e-03,  0.00000000e+00,
  -6.77310571e-04,  5.67567954e-03,  7.90483877e-03,  0.00000000e+00,
  -6.09591836e-03,  7.90483877e-03,  3.35473977e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.17259584e-02,  1.51311525e-03,  4.70006489e-04,  0.00000000e+00,
   1.51311525e-03,  2.81346496e-04,  6.16669131e-05,  0.00000000e+00,
   4.70006489e-04,  6.16669131e-05,  1.47685790e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.72051098e-02,  2.65604397e-03, -3.57514457e-03,  0.00000000e+00,
   2.65604397e-03,  4.68003680e-04, -4.14286333e-04,  0.00000000e+00,
  -3.57514457e-03, -4.14286333e-04,  1.59140918e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.59768197e-02,  5.30709047e-03,  4.16333321e-03,  0.00000000e+00,
   5.30709047e-03,  8.56052618e-04,  5.17433044e-04,  0.00000000e+00,
   4.16333321e-03,  5.17433044e-04,  2.11460050e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.74518041e-02,  2.42559658e-03,  1.24728447e-03,  0.00000000e+00,
   2.42559658e-03,  4.37186478e-04,  1.53026602e-04,  0.00000000e+00,
   1.24728447e-03,  1.53026602e-04,  2.22847238e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.66632421e-02,  2.44709593e-03, -4.50100377e-03,  0.00000000e+00,
   2.44709593e-03,  4.77329013e-04, -3.21799977e-04,  0.00000000e+00,
  -4.50100377e-03, -3.21799977e-04,  2.00718623e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.73052363e-02,  2.34423694e-03,  2.83806841e-03,  0.00000000e+00,
   2.34423694e-03,  4.37209150e-04,  2.70503806e-04,  0.00000000e+00,
   2.83806841e-03,  2.70503806e-04,  1.49408123e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 9.39329434e-03,  1.56224763e-03,  1.46868778e-03,  0.00000000e+00,
   1.56224763e-03,  3.97820142e-04,  3.40959610e-04,  0.00000000e+00,
   1.46868778e-03,  3.40959610e-04,  2.04565637e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.99442934e-02,  2.81124609e-03,  6.67205313e-05,  0.00000000e+00,
   2.81124609e-03,  4.78142203e-04, -1.82647214e-04,  0.00000000e+00,
   6.67205313e-05, -1.82647214e-04,  3.77599299e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.78516561e-02,  4.14279709e-03,  1.55124040e-02,  0.00000000e+00,
   4.14279709e-03,  6.82620914e-04,  2.07179994e-03,  0.00000000e+00,
   1.55124040e-02,  2.07179994e-03,  3.94471958e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.70182008e-02,  3.55682243e-03,  2.13383604e-03,  0.00000000e+00,
   3.55682243e-03,  2.59801047e-03,  3.40657379e-03,  0.00000000e+00,
   2.13383604e-03,  3.40657379e-03,  1.47080747e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.04468446e-02,  1.34988711e-03, -1.48586556e-03,  0.00000000e+00,
   1.34988711e-03,  3.82818806e-04, -1.75409339e-04,  0.00000000e+00,
  -1.48586556e-03, -1.75409339e-04,  9.41611174e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.08039135e-02,  2.82587460e-03, -1.66635436e-03,  0.00000000e+00,
   2.82587460e-03,  5.10295155e-04,  2.92089881e-05,  0.00000000e+00,
  -1.66635436e-03,  2.92089881e-05,  1.80010237e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.85738634e-02,  2.50070798e-03, -1.05502075e-02,  0.00000000e+00,
   2.50070798e-03,  4.45214449e-04, -1.41153485e-03,  0.00000000e+00,
  -1.05502075e-02, -1.41153485e-03,  1.89281162e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.32768226e-02,  3.41464928e-03, -1.63152779e-03,  0.00000000e+00,
   3.41464928e-03,  6.30770868e-04, -5.02214752e-05,  0.00000000e+00,
  -1.63152779e-03, -5.02214752e-05,  1.86594483e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.38922045e-02, -1.70458050e-03, -2.52648909e-03,  0.00000000e+00,
  -1.70458050e-03,  2.24575447e-03,  1.89205038e-03,  0.00000000e+00,
  -2.52648909e-03,  1.89205038e-03,  4.81607066e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.10557247e-02,  1.76097255e-03,  2.22208607e-03,  0.00000000e+00,
   1.76097255e-03,  3.55135096e-04,  5.72899065e-04,  0.00000000e+00,
   2.22208607e-03,  5.72899065e-04,  2.25811321e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.93554666e-02,  3.44968657e-03,  7.93805521e-05,  0.00000000e+00,
   3.44968657e-03,  5.93608618e-03,  1.37681630e-03,  0.00000000e+00,
   7.93805521e-05,  1.37681630e-03,  1.96679356e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.44237259e-02,  3.61537538e-03, -1.98266190e-03,  0.00000000e+00,
   3.61537538e-03,  6.01199223e-04, -1.57741044e-04,  0.00000000e+00,
  -1.98266190e-03, -1.57741044e-04,  8.45909957e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.85135175e-02,  2.19556247e-03, -1.11009227e-03,  0.00000000e+00,
   2.19556247e-03,  3.46448505e-04, -1.26779894e-04,  0.00000000e+00,
  -1.11009227e-03, -1.26779894e-04,  1.09155094e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.41156688e-02,  2.02593650e-03,  4.51821880e-03,  0.00000000e+00,
   2.02593650e-03,  4.16524534e-04,  6.79363671e-04,  0.00000000e+00,
   4.51821880e-03,  6.79363671e-04,  1.78072173e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.43588549e-02,  2.09670281e-03, -5.53655264e-04,  0.00000000e+00,
   2.09670281e-03,  3.76518903e-04,  5.33092716e-05,  0.00000000e+00,
  -5.53655264e-04,  5.33092716e-05,  1.97783597e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.81320813e-02,  2.44519254e-03, -7.85936660e-04,  0.00000000e+00,
   2.44519254e-03,  4.39138821e-04, -1.06063155e-04,  0.00000000e+00,
  -7.85936660e-04, -1.06063155e-04,  1.74655486e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.14719002e-02,  1.46522338e-03,  2.83472706e-03,  0.00000000e+00,
   1.46522338e-03,  2.46057374e-04,  4.65569145e-04,  0.00000000e+00,
   2.83472706e-03,  4.65569145e-04,  2.86489502e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.11632494e-02,  3.15332320e-03,  5.17390249e-03,  0.00000000e+00,
   3.15332320e-03,  6.02436892e-04,  5.14724059e-04,  0.00000000e+00,
   5.17390249e-03,  5.14724059e-04,  1.92836765e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10]]


corrected_wall_cov_2 = [[ 6.25057099e-03, -2.55927216e-06, -1.84891600e-04, -1.64477472e-15,
  -2.55927216e-06,  5.16126347e-05, -4.82739561e-05, -4.73695129e-15,
  -1.84891600e-04, -4.82739561e-05,  2.45784447e-02,  6.57909879e-17,
  -1.64477472e-15, -4.73695129e-15,  6.57909879e-17,  1.00000890e-10],
 [ 1.68605875e-02, -1.52299224e-04,  4.34975978e-03,  0.00000000e+00,
  -1.52299224e-04,  1.58695475e-04, -3.21405212e-04,  0.00000000e+00,
   4.34975978e-03, -3.21405212e-04,  1.08869793e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.16833784e-02, -1.42458346e-04, -1.57160382e-03,  6.00286066e-15,
  -1.42458346e-04,  7.96663080e-05, -1.19841716e-04,  1.96011767e-15,
  -1.57160382e-03, -1.19841716e-04,  1.24345170e-02,  2.08262511e-15,
   6.00286066e-15,  1.96011767e-15,  2.08262511e-15,  1.00000890e-10],
 [ 2.06092764e-02, -1.31338456e-04, -1.19646620e-02,  0.00000000e+00,
  -1.31338456e-04,  8.22296643e-05,  3.00902058e-04,  0.00000000e+00,
  -1.19646620e-02,  3.00902058e-04,  2.14107651e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 5.83976088e-03,  4.01663501e-03,  1.47508443e-04,  0.00000000e+00,
   4.01663501e-03,  1.64237581e-02,  4.80645394e-04,  0.00000000e+00,
   1.47508443e-04,  4.80645394e-04,  2.28557110e-04,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.44703211e-02, -3.14437173e-04, -4.28596558e-03,  0.00000000e+00,
  -3.14437173e-04,  1.02359263e-04,  5.01322269e-04,  0.00000000e+00,
  -4.28596558e-03,  5.01322269e-04,  2.49653589e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 8.97683669e-03, -1.91914340e-04, -1.85999891e-03,  1.21807319e-14,
  -1.91914340e-04,  1.62996614e-04, -1.67669041e-05,  5.00763405e-14,
  -1.85999891e-03, -1.67669041e-05,  4.97669028e-03,  8.45884116e-15,
   1.21807319e-14,  5.00763405e-14,  8.45884116e-15,  1.00003554e-10],
 [ 1.36070484e-02,  1.15808740e-03, -5.47485717e-04,  0.00000000e+00,
   1.15808740e-03,  2.09695399e-02,  6.39609993e-03,  0.00000000e+00,
  -5.47485717e-04,  6.39609993e-03,  6.15743035e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 7.20077287e-03,  8.71255761e-05, -2.54685665e-03, -1.52259149e-15,
   8.71255761e-05,  8.45204559e-05, -5.71177748e-04,  5.07530495e-15,
  -2.54685665e-03, -5.71177748e-04,  2.48173140e-02, -5.07530495e-16,
  -1.52259149e-15,  5.07530495e-15, -5.07530495e-16,  1.00000890e-10],
 [ 2.44990289e-02, -3.31458403e-04,  4.22570040e-04,  0.00000000e+00,
  -3.31458403e-04,  1.15026400e-04,  9.09720984e-05,  0.00000000e+00,
   4.22570040e-04,  9.09720984e-05,  2.49628089e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.78524088e-02, -3.29648698e-04,  1.93296582e-03,  0.00000000e+00,
  -3.29648698e-04,  6.91719865e-03,  2.82765040e-03,  0.00000000e+00,
   1.93296582e-03,  2.82765040e-03,  3.96518363e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.13420838e-02,  7.43632205e-03,  1.88762147e-03,  0.00000000e+00,
   7.43632205e-03,  1.02464352e-02,  4.03300906e-03,  0.00000000e+00,
   1.88762147e-03,  4.03300906e-03,  5.18570701e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.34235078e-02, -6.69370420e-05, -2.58733123e-03,  0.00000000e+00,
  -6.69370420e-05,  9.99758922e-05, -5.39667562e-05,  0.00000000e+00,
  -2.58733123e-03, -5.39667562e-05,  2.77546328e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.28032137e-02,  2.00025999e-04, -6.27061212e-03,  0.00000000e+00,
   2.00025999e-04,  8.05262098e-05, -1.42366407e-05,  0.00000000e+00,
  -6.27061212e-03, -1.42366407e-05,  2.08010841e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.82934813e-02,  4.07902698e-04, -1.02177132e-02,  0.00000000e+00,
   4.07902698e-04,  1.01627746e-04, -1.62322409e-04,  0.00000000e+00,
  -1.02177132e-02, -1.62322409e-04,  2.27979999e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.29467938e-02,  2.90496173e-05, -1.04989600e-03,  0.00000000e+00,
   2.90496173e-05,  9.03329783e-05,  3.32936062e-04,  0.00000000e+00,
  -1.04989600e-03,  3.32936062e-04,  1.71714444e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.25946188e-02,  2.54772673e-03,  1.28098472e-03,  0.00000000e+00,
   2.54772673e-03,  1.60312019e-02,  5.75387944e-03,  0.00000000e+00,
   1.28098472e-03,  5.75387944e-03,  5.42496238e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.29890959e-02,  1.95393532e-05, -2.57966621e-03,  0.00000000e+00,
   1.95393532e-05,  9.84735743e-05,  1.66144848e-04,  0.00000000e+00,
  -2.57966621e-03,  1.66144848e-04,  1.71820670e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.43531447e-02, -2.18285364e-03,  1.16125317e-04,  0.00000000e+00,
  -2.18285364e-03,  6.43006479e-03, -6.83904073e-05,  0.00000000e+00,
   1.16125317e-04, -6.83904073e-05,  1.83056443e-04,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.55992387e-02, -3.58747027e-04, -3.12019954e-03,  0.00000000e+00,
  -3.58747027e-04,  1.15357318e-04,  2.67020605e-05,  0.00000000e+00,
  -3.12019954e-03,  2.67020605e-05,  1.94734242e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.59269050e-02,  3.10256903e-04, -1.51016435e-03,  0.00000000e+00,
   3.10256903e-04,  9.89826731e-05, -3.92309594e-05,  0.00000000e+00,
  -1.51016435e-03, -3.92309594e-05,  1.37325870e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 7.23584322e-03,  3.23749642e-04,  1.32288726e-03,  0.00000000e+00,
   3.23749642e-04,  1.16817107e-04,  3.21492669e-04,  0.00000000e+00,
   1.32288726e-03,  3.21492669e-04,  2.57290751e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.56989843e-02, -1.24113154e-04,  1.67848263e-03,  0.00000000e+00,
  -1.24113154e-04,  8.65437905e-05,  7.35861759e-05,  0.00000000e+00,
   1.67848263e-03,  7.35861759e-05,  2.50308365e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.37711465e-02, -1.60858239e-04, -1.35461870e-03,  1.00660218e-14,
  -1.60858239e-04,  7.37766895e-05, -7.85075736e-06, -6.15803668e-15,
  -1.35461870e-03, -7.85075736e-06,  1.00703286e-02,  2.96059445e-15,
   1.00660218e-14, -6.15803668e-15,  2.96059445e-15,  1.00000890e-10],
 [ 1.92034654e-02,  3.46514018e-04,  2.10550195e-03,  0.00000000e+00,
   3.46514018e-04,  1.22992657e-04, -1.78653936e-04,  0.00000000e+00,
   2.10550195e-03, -1.78653936e-04,  1.26926480e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.72503162e-02,  1.81886440e-04, -2.75832275e-03,  0.00000000e+00,
   1.81886440e-04,  9.68239401e-05, -3.03637498e-04,  0.00000000e+00,
  -2.75832275e-03, -3.03637498e-04,  1.78635865e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.59397144e-02,  3.35407723e-03,  2.30782185e-04,  0.00000000e+00,
   3.35407723e-03,  1.66844092e-02,  1.40328892e-03,  0.00000000e+00,
   2.30782185e-04,  1.40328892e-03,  6.37290825e-04,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.32768527e-02,  2.21397218e-04,  6.13653520e-03,  0.00000000e+00,
   2.21397218e-04,  7.05971761e-05, -1.18320153e-04,  0.00000000e+00,
   6.13653520e-03, -1.18320153e-04,  2.23608445e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.56788249e-02, -4.41008992e-03, -3.11801996e-04,  0.00000000e+00,
  -4.41008992e-03,  1.65132638e-02,  5.10588428e-03,  0.00000000e+00,
  -3.11801996e-04,  5.10588428e-03,  4.19537351e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.76143311e-02,  1.89785394e-04,  1.47852127e-03,  0.00000000e+00,
   1.89785394e-04,  8.64301619e-05,  3.70449561e-05,  0.00000000e+00,
   1.47852127e-03,  3.70449561e-05,  2.30009183e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.74378268e-02,  4.48661216e-04,  2.83755432e-03,  0.00000000e+00,
   4.48661216e-04,  1.03308346e-04, -1.11658534e-04,  0.00000000e+00,
   2.83755432e-03, -1.11658534e-04,  1.09170126e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.26912219e-02,  3.09093361e-04, -2.46697315e-03,  0.00000000e+00,
   3.09093361e-04,  1.53395187e-04, -8.53984329e-06,  0.00000000e+00,
  -2.46697315e-03, -8.53984329e-06,  8.76924489e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.18873397e-02,  9.64065330e-05,  2.23232957e-04,  0.00000000e+00,
   9.64065330e-05,  1.17923046e-04,  9.09977825e-05,  0.00000000e+00,
   2.23232957e-04,  9.09977825e-05,  1.19086197e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.55017488e-02,  5.09086349e-05, -1.79657736e-03,  0.00000000e+00,
   5.09086349e-05,  8.02801587e-05,  1.25132894e-04,  0.00000000e+00,
  -1.79657736e-03,  1.25132894e-04,  2.27296036e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.76864769e-02, -2.72727804e-04,  3.55944532e-04,  0.00000000e+00,
  -2.72727804e-04,  1.00382385e-04, -1.32453279e-04,  0.00000000e+00,
   3.55944532e-04, -1.32453279e-04,  1.67795587e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.56789906e-02, -2.78348499e-03,  3.10036325e-04,  0.00000000e+00,
  -2.78348499e-03,  4.88178991e-03,  4.33139270e-03,  0.00000000e+00,
   3.10036325e-04,  4.33139270e-03,  1.16665866e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.26404436e-02,  2.71089782e-04,  3.20587214e-03,  0.00000000e+00,
   2.71089782e-04,  8.95871999e-05, -4.56266207e-05,  0.00000000e+00,
   3.20587214e-03, -4.56266207e-05,  1.76950525e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.43148424e-02,  8.22579095e-05, -3.23963206e-04,  0.00000000e+00,
   8.22579095e-05,  1.04839666e-04,  2.45111965e-04,  0.00000000e+00,
  -3.23963206e-04,  2.45111965e-04,  1.80011988e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.85861643e-02, -2.46044737e-03,  3.74282041e-04,  0.00000000e+00,
  -2.46044737e-03,  4.73545399e-03, -1.54123714e-04,  0.00000000e+00,
   3.74282041e-04, -1.54123714e-04,  2.30202408e-04,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.56934110e-02,  3.20808060e-04, -1.24231074e-03,  0.00000000e+00,
   3.20808060e-04,  1.18538599e-04,  9.56307413e-05,  0.00000000e+00,
  -1.24231074e-03,  9.56307413e-05,  1.62410848e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.13932376e-02,  1.47108105e-04, -7.36662187e-03,  0.00000000e+00,
   1.47108105e-04,  1.47333296e-04,  7.40623218e-05,  0.00000000e+00,
  -7.36662187e-03,  7.40623218e-05,  2.10817773e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.53261367e-02, -2.20398160e-05,  6.03014429e-04,  0.00000000e+00,
  -2.20398160e-05,  8.59224892e-05, -2.49144068e-04,  0.00000000e+00,
   6.03014429e-04, -2.49144068e-04,  1.52461110e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.69515759e-02, -1.21541467e-04, -3.64980171e-03,  0.00000000e+00,
  -1.21541467e-04,  9.51205147e-05,  4.83587879e-04,  0.00000000e+00,
  -3.64980171e-03,  4.83587879e-04,  2.04110872e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.75669603e-02,  1.51907545e-04,  9.22470063e-04,  0.00000000e+00,
   1.51907545e-04,  1.10933470e-04, -1.72520813e-04,  0.00000000e+00,
   9.22470063e-04, -1.72520813e-04,  1.99384913e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.43839652e-02, -1.10478999e-04, -4.35444672e-04,  0.00000000e+00,
  -1.10478999e-04,  1.01170903e-04, -1.48801380e-04,  0.00000000e+00,
  -4.35444672e-04, -1.48801380e-04,  1.42220147e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.09763397e-02,  7.82035571e-03,  6.93992421e-04,  0.00000000e+00,
   7.82035571e-03,  2.22936254e-02,  2.59600184e-03,  0.00000000e+00,
   6.93992421e-04,  2.59600184e-03,  1.32496085e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.47664398e-02,  6.90687011e-05, -1.12958497e-03,  0.00000000e+00,
   6.90687011e-05,  7.92396022e-05,  1.20718993e-04,  0.00000000e+00,
  -1.12958497e-03,  1.20718993e-04,  1.34094339e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.64454412e-02, -8.30728459e-06,  3.61627224e-03,  0.00000000e+00,
  -8.30728459e-06,  9.16888093e-05, -1.82149612e-04,  0.00000000e+00,
   3.61627224e-03, -1.82149612e-04,  1.42099038e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.51095474e-02, -1.27068881e-04, -7.34796328e-03,  0.00000000e+00,
  -1.27068881e-04,  9.88507018e-05, -2.50703073e-04,  0.00000000e+00,
  -7.34796328e-03, -2.50703073e-04,  2.53503118e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.45976916e-02,  2.06065044e-04,  3.93983675e-03,  0.00000000e+00,
   2.06065044e-04,  1.16279640e-04, -1.53023630e-05,  0.00000000e+00,
   3.93983675e-03, -1.53023630e-05,  1.95804778e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.88147910e-02, -2.76640253e-06, -2.17075041e-03,  0.00000000e+00,
  -2.76640253e-06,  1.01456179e-04, -1.23022808e-04,  0.00000000e+00,
  -2.17075041e-03, -1.23022808e-04,  1.57499742e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.03499773e-03,  1.07108848e-04, -1.57820177e-03,  9.36624469e-15,
   1.07108848e-04,  1.30780158e-04,  7.07823026e-04,  2.77757587e-14,
  -1.57820177e-03,  7.07823026e-04,  2.20184457e-02,  3.39122642e-15,
   9.36624469e-15,  2.77757587e-14,  3.39122642e-15,  1.00000890e-10],
 [ 8.49098712e-03, -1.31981703e-03,  3.64227089e-05,  0.00000000e+00,
  -1.31981703e-03,  3.94419581e-03, -8.21736467e-06,  0.00000000e+00,
   3.64227089e-05, -8.21736467e-06,  2.84234906e-04,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.43378628e-02, -1.75190147e-03,  1.65384018e-03,  0.00000000e+00,
  -1.75190147e-03,  4.29766485e-03,  2.14653951e-03,  0.00000000e+00,
   1.65384018e-03,  2.14653951e-03,  5.57164289e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10]]





noisy_default = [[ 9.65566840e-03,  1.28155947e-03, -2.63343193e-03,  0.00000000e+00,
   1.28155947e-03,  2.84917362e-04, -2.86609778e-04,  0.00000000e+00,
  -2.63343193e-03, -2.86609778e-04,  7.55697628e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.11912899e-02,  1.75002730e-03,  1.06681313e-03,  1.36424194e-14,
   1.75002730e-03,  3.65413405e-04,  8.68475254e-05, -1.13686825e-15,
   1.06681313e-03,  8.68475254e-05,  8.46296921e-03,  4.26325616e-15,
   1.36424194e-14, -1.13686825e-15,  4.26325616e-15,  1.00000890e-10],
 [ 1.08419647e-02,  1.25909306e-03,  4.35506263e-05,  0.00000000e+00,
   1.25909306e-03,  2.76323961e-04,  2.39472880e-04,  0.00000000e+00,
   4.35506263e-05,  2.39472880e-04,  1.15295788e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.02830697e-02,  1.40774006e-03,  2.37997388e-03,  2.36847556e-14,
   1.40774006e-03,  2.62402900e-04,  1.92164414e-04,  4.73695087e-15,
   2.37997388e-03,  1.92164414e-04,  4.68599098e-03,  2.07241603e-15,
   2.36847556e-14,  4.73695087e-15,  2.07241603e-15,  1.00003554e-10],
 [ 1.08206207e-02,  1.67605374e-03,  2.19153333e-03,  0.00000000e+00,
   1.67605374e-03,  3.49144480e-04,  3.12614604e-04,  0.00000000e+00,
   2.19153333e-03,  3.12614604e-04,  9.07050818e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.40246013e-03,  4.75675013e-04, -1.14665600e-03,  3.55271347e-16,
   4.75675013e-04,  2.09554128e-04, -1.85862809e-04,  1.01844455e-14,
  -1.14665600e-03, -1.85862809e-04,  7.24381488e-03, -2.36847564e-16,
   3.55271347e-16,  1.01844455e-14, -2.36847564e-16,  1.00000890e-10],
 [ 6.20089285e-03,  8.65629467e-04, -4.49415063e-03,  2.22044571e-14,
   8.65629467e-04,  1.54836773e-04, -7.06772378e-04,  2.30926355e-14,
  -4.49415063e-03, -7.06772378e-04,  1.12829953e-02,  8.43769414e-15,
   2.22044571e-14,  2.30926355e-14,  8.43769414e-15,  1.00003554e-10],
 [ 8.78622849e-03,  1.47853815e-03, -4.51415137e-04,  0.00000000e+00,
   1.47853815e-03,  3.55545490e-04, -1.59961419e-04,  0.00000000e+00,
  -4.51415137e-04, -1.59961419e-04,  1.38339205e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.12471990e-02,  1.41306582e-03,  5.03765233e-03, -9.16829309e-16,
   1.41306582e-03,  2.87174946e-04,  9.16705816e-04,  1.19187810e-14,
   5.03765233e-03,  9.16705816e-04,  9.87298228e-03,  2.40667683e-15,
  -9.16829309e-16,  1.19187810e-14,  2.40667683e-15,  1.00000890e-10],
 [ 8.70910566e-03,  1.34580699e-03,  1.85792707e-03,  0.00000000e+00,
   1.34580699e-03,  2.82780995e-04,  4.79075461e-05,  0.00000000e+00,
   1.85792707e-03,  4.79075461e-05,  1.41748805e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 7.59006757e-03,  8.68240546e-04,  2.70106783e-03,  0.00000000e+00,
   8.68240546e-04,  2.90797965e-04,  2.95005215e-04,  0.00000000e+00,
   2.70106783e-03,  2.95005215e-04,  1.26700522e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.26816761e-02,  1.97180081e-03,  2.45546270e-03,  9.17784254e-15,
   1.97180081e-03,  3.49995884e-04,  3.92304210e-04,  1.00660210e-14,
   2.45546270e-03,  3.92304210e-04,  6.14209659e-03,  2.36847564e-15,
   9.17784254e-15,  1.00660210e-14,  2.36847564e-15,  1.00000890e-10],
 [ 1.63591765e-02,  2.22603581e-03, -2.00984767e-03,  0.00000000e+00,
   2.22603581e-03,  3.97017604e-04,  1.05192175e-05,  0.00000000e+00,
  -2.00984767e-03,  1.05192175e-05,  1.06262369e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.11712590e-02,  1.58378948e-03,  8.27705080e-05,  1.05160318e-14,
   1.58378948e-03,  2.79379252e-04, -2.75287864e-04,  1.13686825e-15,
   8.27705080e-05, -2.75287864e-04,  8.09112564e-03,  2.06057387e-15,
   1.05160318e-14,  1.13686825e-15,  2.06057387e-15,  1.00000890e-10],
 [ 1.68184787e-02,  2.19959207e-03, -1.84056431e-03,  0.00000000e+00,
   2.19959207e-03,  3.80806247e-04, -1.53617948e-04,  0.00000000e+00,
  -1.84056431e-03, -1.53617948e-04,  6.36783009e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.42470654e-02,  1.67749554e-03, -2.20969319e-03,  0.00000000e+00,
   1.67749554e-03,  2.44504947e-04, -3.61552520e-04,  0.00000000e+00,
  -2.20969319e-03, -3.61552520e-04,  7.60684162e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 8.00698716e-03,  1.25766231e-03,  8.21632450e-04,  0.00000000e+00,
   1.25766231e-03,  2.89979682e-04,  2.69048993e-04,  0.00000000e+00,
   8.21632450e-04,  2.69048993e-04,  1.13143316e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 6.23814575e-03,  8.84727750e-04,  2.24126037e-03,  1.58257230e-14,
   8.84727750e-04,  1.76342102e-04,  1.44315010e-04,  2.97136041e-14,
   2.24126037e-03,  1.44315010e-04,  1.48744751e-02,  8.07434845e-16,
   1.58257230e-14,  2.97136041e-14,  8.07434845e-16,  1.00000890e-10],
 [ 1.18116299e-02,  1.83297670e-03,  3.33082542e-04,  0.00000000e+00,
   1.83297670e-03,  3.64807376e-04, -5.82114262e-05,  0.00000000e+00,
   3.33082542e-04, -5.82114262e-05,  1.50764510e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.03207007e-02,  1.34900340e-03, -3.80988873e-04,  0.00000000e+00,
   1.34900340e-03,  3.17424478e-04, -1.55999456e-04,  0.00000000e+00,
  -3.80988873e-04, -1.55999456e-04,  1.03485901e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.17670847e-02,  1.58316304e-03,  2.13862746e-04,  5.15716476e-15,
   1.58316304e-03,  3.15187295e-04,  4.51746491e-05,  1.19187810e-14,
   2.13862746e-04,  4.51746491e-05,  4.89830831e-03,  4.12573189e-15,
   5.15716476e-15,  1.19187810e-14,  4.12573189e-15,  1.00000890e-10],
 [ 9.20685008e-03,  1.25884393e-03,  2.70546693e-03,  0.00000000e+00,
   1.25884393e-03,  2.55703984e-04,  7.46920239e-04,  0.00000000e+00,
   2.70546693e-03,  7.46920239e-04,  1.09457020e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.77886835e-03,  4.17723262e-04, -4.10565757e-04,  0.00000000e+00,
   4.17723262e-04,  1.49043102e-04, -8.07553952e-05,  0.00000000e+00,
  -4.10565757e-04, -8.07553952e-05,  8.10072199e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 6.15700614e-03,  4.34858783e-04,  8.65471200e-04,  7.56970157e-16,
   4.34858783e-04,  1.71628199e-04,  1.17387601e-04,  1.25959839e-14,
   8.65471200e-04,  1.17387601e-04,  2.22290400e-03,  7.26691334e-15,
   7.56970157e-16,  1.25959839e-14,  7.26691334e-15,  1.00000890e-10],
 [ 8.90567154e-03,  1.32675283e-03,  5.37930522e-04,  1.23410041e-14,
   1.32675283e-03,  3.75175063e-04,  1.25829320e-04,  8.97527546e-15,
   5.37930522e-04,  1.25829320e-04,  2.62440112e-03,  5.60954727e-15,
   1.23410041e-14,  8.97527546e-15,  5.60954727e-15,  1.00003554e-10],
 [ 8.71067867e-03,  1.30061095e-03,  1.06191484e-03,  0.00000000e+00,
   1.30061095e-03,  2.96583283e-04,  2.86646173e-05,  0.00000000e+00,
   1.06191484e-03,  2.86646173e-05,  6.75395736e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.50489723e-02,  2.25569634e-03,  1.71556219e-03,  1.23687063e-14,
   2.25569634e-03,  4.28918924e-04,  2.26970282e-04,  2.42110849e-14,
   1.71556219e-03,  2.26970282e-04,  6.38194615e-03,  1.31581984e-15,
   1.23687063e-14,  2.42110849e-14,  1.31581984e-15,  1.00000890e-10],
 [ 1.17385192e-02,  1.52706110e-03,  5.15379186e-04,  0.00000000e+00,
   1.52706110e-03,  2.87851959e-04, -9.15320270e-05,  0.00000000e+00,
   5.15379186e-04, -9.15320270e-05,  7.49113131e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.13694714e-02,  1.37706927e-03, -1.52729230e-03,  0.00000000e+00,
   1.37706927e-03,  2.68152304e-04, -4.17921081e-04,  0.00000000e+00,
  -1.52729230e-03, -4.17921081e-04,  4.28377977e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.08965598e-02,  1.50094670e-03,  1.63106201e-03,  0.00000000e+00,
   1.50094670e-03,  2.99664738e-04,  3.75662203e-04,  0.00000000e+00,
   1.63106201e-03,  3.75662203e-04,  7.41702458e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 9.54150502e-03,  1.39730773e-03, -8.86848895e-04,  0.00000000e+00,
   1.39730773e-03,  2.79172877e-04, -3.97902273e-04,  0.00000000e+00,
  -8.86848895e-04, -3.97902273e-04,  1.16201518e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.07572414e-02,  1.62888330e-03,  2.89938436e-03,  3.42113135e-15,
   1.62888330e-03,  3.34277167e-04,  3.37538397e-04,  8.42124645e-15,
   2.89938436e-03,  3.37538397e-04,  7.20019406e-03,  3.68429559e-15,
   3.42113135e-15,  8.42124645e-15,  3.68429559e-15,  1.00000890e-10],
 [ 9.28449724e-03,  1.43626169e-03, -1.51222991e-03,  2.73285651e-15,
   1.43626169e-03,  2.93804536e-04, -2.12471874e-04,  1.42108539e-14,
  -1.51222991e-03, -2.12471874e-04,  9.61977988e-03,  1.22978543e-15,
   2.73285651e-15,  1.42108539e-14,  1.22978543e-15,  1.00000890e-10],
 [ 6.22325344e-03,  1.09905319e-03,  3.66111519e-03,  2.55795361e-14,
   1.09905319e-03,  2.69575161e-04,  6.79418852e-04,  3.69482175e-14,
   3.66111519e-03,  6.79418852e-04,  1.53976902e-02, -4.26325616e-15,
   2.55795361e-14,  3.69482175e-14, -4.26325616e-15,  1.00003554e-10],
 [ 4.24541626e-03,  4.59604838e-04, -1.89991132e-03,  3.94745941e-15,
   4.59604838e-04,  1.35348790e-04, -2.16977438e-04,  2.52637385e-14,
  -1.89991132e-03, -2.16977438e-04,  9.47539881e-03, -1.97372970e-15,
   3.94745941e-15,  2.52637385e-14, -1.97372970e-15,  1.00003554e-10],
 [ 8.61179922e-03,  1.20097294e-03,  5.58874344e-05,  0.00000000e+00,
   1.20097294e-03,  3.20344378e-04,  2.20968450e-05,  0.00000000e+00,
   5.58874344e-05,  2.20968450e-05,  6.33707643e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 7.16387294e-03,  1.22839690e-03, -3.29533895e-03,  4.90029418e-16,
   1.22839690e-03,  3.70991940e-04, -3.35377466e-04, -6.86041207e-15,
  -3.29533895e-03, -3.35377466e-04,  1.14034051e-02,  1.71510302e-15,
   4.90029418e-16, -6.86041207e-15,  1.71510302e-15,  1.00000890e-10],
 [ 3.66904540e-03,  5.64240676e-04,  2.89248931e-03,  4.40536449e-14,
   5.64240676e-04,  1.38571006e-04,  3.89477122e-04,  1.70530246e-14,
   2.89248931e-03,  3.89477122e-04,  8.85080267e-03,  2.22044584e-15,
   4.40536449e-14,  1.70530246e-14,  2.22044584e-15,  1.00003554e-10],
 [ 8.13114922e-03,  7.47421815e-04, -1.52007223e-03,  0.00000000e+00,
   7.47421815e-04,  2.13542793e-04, -3.48448375e-04,  0.00000000e+00,
  -1.52007223e-03, -3.48448375e-04,  4.81084781e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.75682157e-02,  2.16863491e-03,  3.33167147e-04,  3.12638781e-15,
   2.16863491e-03,  3.56699486e-04, -6.24558670e-05,  2.10320636e-14,
   3.33167147e-04, -6.24558670e-05,  2.90784985e-03,  1.42108531e-16,
   3.12638781e-15,  2.10320636e-14,  1.42108531e-16,  1.00000890e-10],
 [ 6.82695629e-03,  1.09673094e-03, -2.87985709e-03,  1.49587933e-14,
   1.09673094e-03,  2.29661775e-04, -5.98087558e-04,  5.38516544e-14,
  -2.87985709e-03, -5.98087558e-04,  1.08735729e-02,  7.47939622e-16,
   1.49587933e-14,  5.38516544e-14,  7.47939622e-16,  1.00003554e-10],
 [ 7.15011265e-03,  7.69437873e-04,  6.67557935e-04,  0.00000000e+00,
   7.69437873e-04,  1.92536987e-04,  9.94186848e-07,  0.00000000e+00,
   6.67557935e-04,  9.94186848e-07,  6.38166582e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 6.09858055e-03,  1.06478622e-03, -1.93985645e-04, -2.29207327e-16,
   1.06478622e-03,  2.82751280e-04, -1.12533235e-04,  2.29207319e-14,
  -1.93985645e-04, -1.12533235e-04,  7.95732252e-03,  5.61557941e-15,
  -2.29207327e-16,  2.29207319e-14,  5.61557941e-15,  1.00000890e-10],
 [ 7.57119246e-03,  9.37659002e-04, -4.00484866e-03,  0.00000000e+00,
   9.37659002e-04,  2.53271515e-04, -5.40340552e-04,  0.00000000e+00,
  -4.00484866e-03, -5.40340552e-04,  1.00176064e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.18967276e-02,  1.77551887e-03,  8.24507326e-04,  1.23572641e-15,
   1.77551887e-03,  3.25533183e-04,  1.24037848e-04,  1.05036744e-14,
   8.24507326e-04,  1.24037848e-04,  5.06379921e-03,  1.69912374e-15,
   1.23572641e-15,  1.05036744e-14,  1.69912374e-15,  1.00000890e-10],
 [ 7.36650918e-03,  6.37225865e-04, -1.14267095e-04,  1.68753883e-14,
   6.37225865e-04,  1.14756782e-04, -4.17083676e-04,  1.06581402e-14,
  -1.14267095e-04, -4.17083676e-04,  5.15426742e-03,  1.77635663e-15,
   1.68753883e-14,  1.06581402e-14,  1.77635663e-15,  1.00003554e-10],
 [ 1.13269761e-02,  1.52604945e-03, -1.27430412e-03,  8.62801821e-15,
   1.52604945e-03,  2.71279278e-04,  5.41568006e-05,  1.42108539e-14,
  -1.27430412e-03,  5.41568006e-05,  8.56457371e-03,  3.29894811e-15,
   8.62801821e-15,  1.42108539e-14,  3.29894811e-15,  1.00000890e-10],
 [ 9.48536769e-03,  1.27287710e-03,  5.82224689e-04,  7.10542693e-15,
   1.27287710e-03,  2.84223061e-04,  1.22372396e-04,  1.63161653e-14,
   5.82224689e-04,  1.22372396e-04,  7.38992449e-03,  4.01325015e-15,
   7.10542693e-15,  1.63161653e-14,  4.01325015e-15,  1.00000890e-10],
 [ 9.58025176e-03,  1.39318255e-03,  1.80391758e-03,  2.23689374e-15,
   1.39318255e-03,  2.58653163e-04,  3.74994619e-04,  1.21055425e-14,
   1.80391758e-03,  3.74994619e-04,  5.24193887e-03,  4.73695129e-15,
   2.23689374e-15,  1.21055425e-14,  4.73695129e-15,  1.00000890e-10],
 [ 7.38379918e-03,  1.05337030e-03,  1.54893933e-04,  3.87568734e-15,
   1.05337030e-03,  2.27797820e-04,  9.82831843e-05,  2.13162804e-14,
   1.54893933e-04,  9.82831843e-05,  5.86546212e-03,  5.00609601e-15,
   3.87568734e-15,  2.13162804e-14,  5.00609601e-15,  1.00000890e-10],]



cleaner_in_plane_gauss = [[ 2.04458125e-02, -2.04941476e-04,  4.14228393e-03,  0.00000000e+00,
  -2.04941476e-04,  8.51083460e-05, -1.10668567e-04,  0.00000000e+00,
   4.14228393e-03, -1.10668567e-04,  2.06957664e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.08262708e-02,  5.69321710e-05,  7.57524511e-03,  0.00000000e+00,
   5.69321710e-05,  9.21313112e-05,  1.87409678e-04,  0.00000000e+00,
   7.57524511e-03,  1.87409678e-04,  1.69311706e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 8.00311938e-03,  3.43189095e-05,  3.91325622e-04,  0.00000000e+00,
   3.43189095e-05,  1.06570005e-04, -2.87195202e-04,  0.00000000e+00,
   3.91325622e-04, -2.87195202e-04,  2.38442533e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.83870215e-02, -2.32653023e-04,  2.85351928e-03,  0.00000000e+00,
  -2.32653023e-04,  1.21877820e-04,  1.35143244e-04,  0.00000000e+00,
   2.85351928e-03,  1.35143244e-04,  1.60308816e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.69167593e-02, -2.96586186e-05,  1.26333919e-03,  0.00000000e+00,
  -2.96586186e-05,  8.16779793e-05,  6.36985351e-05,  0.00000000e+00,
   1.26333919e-03,  6.36985351e-05,  1.43935867e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.52372671e-02, -2.82623980e-04,  2.51299539e-03,  0.00000000e+00,
  -2.82623980e-04,  1.03746563e-04,  2.28500667e-05,  0.00000000e+00,
   2.51299539e-03,  2.28500667e-05,  1.73015315e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 4.07745503e-02,  2.73959769e-04, -1.11989281e-03,  0.00000000e+00,
   2.73959769e-04,  9.51809125e-05, -1.08263790e-04,  0.00000000e+00,
  -1.11989281e-03, -1.08263790e-04,  9.45248641e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.97280515e-02,  1.36690447e-04,  1.09189458e-03,  0.00000000e+00,
   1.36690447e-04,  8.18606495e-05,  8.29514247e-05,  0.00000000e+00,
   1.09189458e-03,  8.29514247e-05,  8.55301227e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.55229266e-02,  2.51386518e-04,  1.67467573e-03,  0.00000000e+00,
   2.51386518e-04,  1.15303133e-04, -2.91103468e-04,  0.00000000e+00,
   1.67467573e-03, -2.91103468e-04,  8.92524794e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.55250756e-02, -4.94719607e-05, -1.75828743e-03,  0.00000000e+00,
  -4.94719607e-05,  1.07230917e-04, -3.51404997e-05,  0.00000000e+00,
  -1.75828743e-03, -3.51404997e-05,  1.79888923e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.06414533e-02,  4.72225394e-04,  2.54298002e-03, -3.35534039e-15,
   4.72225394e-04,  9.22999679e-05,  1.80931020e-05, -3.15796731e-15,
   2.54298002e-03,  1.80931020e-05,  2.36200960e-03,  9.07915643e-15,
  -3.35534039e-15, -3.15796731e-15,  9.07915643e-15,  1.00003554e-10],
 [ 2.11914983e-02,  1.91544925e-04, -1.46785064e-03,  0.00000000e+00,
   1.91544925e-04,  8.37180050e-05, -6.73537215e-05,  0.00000000e+00,
  -1.46785064e-03, -6.73537215e-05,  1.61707010e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.31764987e-02, -1.95236920e-04, -1.03118708e-02,  0.00000000e+00,
  -1.95236920e-04,  9.46374203e-05,  6.27524205e-05,  0.00000000e+00,
  -1.03118708e-02,  6.27524205e-05,  2.46915836e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.95893420e-02, -2.10572485e-04, -3.37774603e-04,  0.00000000e+00,
  -2.10572485e-04,  1.04108920e-04,  2.75482453e-04,  0.00000000e+00,
  -3.37774603e-04,  2.75482453e-04,  1.23351458e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 8.88098497e-03, -3.53789364e-04, -2.26527438e-04, -4.79616313e-15,
  -3.53789364e-04,  9.77857853e-05, -1.26241517e-04, -1.36424194e-14,
  -2.26527438e-04, -1.26241517e-04,  1.74225084e-02,  5.68434123e-16,
  -4.79616313e-15, -1.36424194e-14,  5.68434123e-16,  1.00000890e-10],
 [ 1.08872615e-02, -1.42559293e-04, -2.93516694e-03,  0.00000000e+00,
  -1.42559293e-04,  1.07382868e-04, -8.93774777e-05,  0.00000000e+00,
  -2.93516694e-03, -8.93774777e-05,  1.82399061e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.60883216e-02, -2.31409911e-04, -1.98222254e-03,  0.00000000e+00,
  -2.31409911e-04,  9.50338435e-05, -3.46528337e-04,  0.00000000e+00,
  -1.98222254e-03, -3.46528337e-04,  1.84142813e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.68398339e-02, -1.34612521e-04,  1.85111747e-03,  0.00000000e+00,
  -1.34612521e-04,  1.34547037e-04,  9.22485706e-05,  0.00000000e+00,
   1.85111747e-03,  9.22485706e-05,  8.57389346e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.64139883e-02,  1.62631677e-05, -6.83655147e-04,  0.00000000e+00,
   1.62631677e-05,  1.06676314e-04, -4.89793427e-04,  0.00000000e+00,
  -6.83655147e-04, -4.89793427e-04,  2.45512128e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.81934384e-02,  3.71804665e-04,  4.73104464e-03,  0.00000000e+00,
   3.71804665e-04,  1.04153187e-04,  1.15475952e-04,  0.00000000e+00,
   4.73104464e-03,  1.15475952e-04,  1.32984426e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.73545198e-02,  3.25499204e-05, -2.79195723e-04,  0.00000000e+00,
   3.25499204e-05,  8.57765044e-05,  1.56147682e-04,  0.00000000e+00,
  -2.79195723e-04,  1.56147682e-04,  1.26882456e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.99038591e-02, -6.06727262e-05, -5.44526847e-03,  0.00000000e+00,
  -6.06727262e-05,  7.23806224e-05,  1.57198592e-04,  0.00000000e+00,
  -5.44526847e-03,  1.57198592e-04,  2.09291968e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.00586636e-02, -1.39214671e-05, -4.39512497e-03,  0.00000000e+00,
  -1.39214671e-05,  9.19652593e-05, -8.10927595e-05,  0.00000000e+00,
  -4.39512497e-03, -8.10927595e-05,  2.14921366e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.67850982e-02, -1.97004221e-04, -3.45942960e-03,  0.00000000e+00,
  -1.97004221e-04,  1.59573581e-04,  1.45979893e-05,  0.00000000e+00,
  -3.45942960e-03,  1.45979893e-05,  1.47080077e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.86476519e-02,  1.90454652e-04,  4.03811573e-04,  0.00000000e+00,
   1.90454652e-04,  7.60805779e-05,  2.50832149e-04,  0.00000000e+00,
   4.03811573e-04,  2.50832149e-04,  1.39934346e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.37614382e-02,  5.10351849e-04,  1.78653991e-03,  0.00000000e+00,
   5.10351849e-04,  1.12481473e-04, -8.13267397e-05,  0.00000000e+00,
   1.78653991e-03, -8.13267397e-05,  8.49646330e-03,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.09120493e-02, -2.60658126e-05,  6.73154776e-04,  0.00000000e+00,
  -2.60658126e-05,  1.21939047e-04,  5.93525729e-05,  0.00000000e+00,
   6.73154776e-04,  5.93525729e-05,  1.91637352e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.23243253e-02, -2.26049069e-05, -3.75891593e-03,  0.00000000e+00,
  -2.26049069e-05,  1.08054854e-04, -4.33099813e-05,  0.00000000e+00,
  -3.75891593e-03, -4.33099813e-05,  1.07830940e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.12697517e-02,  2.10399012e-04,  1.47845026e-03,  0.00000000e+00,
   2.10399012e-04,  1.06361069e-04, -1.77181166e-04,  0.00000000e+00,
   1.47845026e-03, -1.77181166e-04,  2.03231666e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 3.70942988e-03, -2.96508260e-05, -1.64778868e-03, -1.53950917e-15,
  -2.96508260e-05,  6.57451819e-05, -6.14683158e-05,  2.55795361e-14,
  -1.64778868e-03, -6.14683158e-05,  1.22287646e-02,  9.47390258e-16,
  -1.53950917e-15,  2.55795361e-14,  9.47390258e-16,  1.00000890e-10],
 [ 1.55442487e-02,  8.74429388e-05,  2.04568729e-03,  0.00000000e+00,
   8.74429388e-05,  7.39689785e-05, -4.35418879e-05,  0.00000000e+00,
   2.04568729e-03, -4.35418879e-05,  1.76246483e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.29373930e-02,  1.09909679e-05, -1.78692862e-04,  0.00000000e+00,
   1.09909679e-05,  9.88965912e-05,  2.31687649e-04,  0.00000000e+00,
  -1.78692862e-04,  2.31687649e-04,  1.80978812e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.29281338e-02,  3.71408794e-04, -4.52518649e-03, -3.99680247e-15,
   3.71408794e-04,  8.28233096e-05, -6.91087451e-04,  3.27942782e-15,
  -4.52518649e-03, -6.91087451e-04,  1.44502074e-02,  2.73285651e-16,
  -3.99680247e-15,  3.27942782e-15,  2.73285651e-16,  1.00000890e-10],
 [ 2.18809694e-02, -1.42590943e-05,  1.16234960e-03,  0.00000000e+00,
  -1.42590943e-05,  7.63136268e-05, -6.92243266e-05,  0.00000000e+00,
   1.16234960e-03, -6.92243266e-05,  1.20330984e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 2.69233771e-02, -6.78800861e-04, -1.25241105e-03,  0.00000000e+00,
  -6.78800861e-04,  8.86484559e-05, -4.10307948e-05,  0.00000000e+00,
  -1.25241105e-03, -4.10307948e-05,  1.00805769e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.52336741e-02,  1.52955501e-04,  5.97203383e-03,  0.00000000e+00,
   1.52955501e-04,  6.47477646e-05, -3.86845859e-05,  0.00000000e+00,
   5.97203383e-03, -3.86845859e-05,  1.79207604e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.07566137e-02, -4.22615907e-04, -5.36616950e-04,  0.00000000e+00,
  -4.22615907e-04,  1.28341038e-04,  2.40224384e-04,  0.00000000e+00,
  -5.36616950e-04,  2.40224384e-04,  2.04680245e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.27185872e-02,  1.78528971e-05, -2.90005282e-03,  0.00000000e+00,
   1.78528971e-05,  6.12400254e-05, -6.12546614e-07,  0.00000000e+00,
  -2.90005282e-03, -6.12546614e-07,  1.78487059e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.58362463e-02, -2.75753664e-05,  2.59149121e-03,  0.00000000e+00,
  -2.75753664e-05,  1.52858818e-04, -4.31266380e-04,  0.00000000e+00,
   2.59149121e-03, -4.31266380e-04,  1.12099526e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],
 [ 1.37641178e-02, -6.37778503e-05,  5.66723617e-03,  1.18423782e-16,
  -6.37778503e-05,  8.10144338e-05, -3.81899445e-05, -1.42108539e-15,
   5.66723617e-03, -3.81899445e-05,  1.41321076e-02,  1.65793295e-15,
   1.18423782e-16, -1.42108539e-15,  1.65793295e-15,  1.00000890e-10],
 [ 1.93247050e-02,  1.44391524e-04,  3.27568327e-04,  0.00000000e+00,
   1.44391524e-04,  1.08110791e-04, -1.34621187e-05,  0.00000000e+00,
   3.27568327e-04, -1.34621187e-05,  1.06878737e-02,  0.00000000e+00,
   0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000001e-10],]

In [46]:
# default_wall = np.array(default_wall_90_deg)
# default_wall = np.array(default_wall_cov_2)
default_wall = np.array(noisy_default)
default_wall = default_wall.reshape(default_wall.shape[0], 4, 4)
default_wall = default_wall[:,0:3, 0:3]
default_wall.shape

(50, 3, 3)

In [47]:
# corrected_wall = np.array(corrected_wall_90_deg)
# corrected_wall = np.array(corrected_wall_cov_2)
corrected_wall = np.array(cleaner_in_plane_gauss)
corrected_wall.shape
corrected_wall = corrected_wall.reshape(corrected_wall.shape[0],4,4)
corrected_wall = corrected_wall[:, 0:3, 0:3]
corrected_wall.shape

(41, 3, 3)

In [48]:
default_wall.mean(axis=0)

array([[9.47691676e-03, 1.30489712e-03, 1.92965032e-04],
       [1.30489712e-03, 2.78397036e-04, 1.20224436e-05],
       [1.92965032e-04, 1.20224436e-05, 8.44171709e-03]])

In [49]:
corrected_wall.mean(axis=0)

array([[ 2.01425446e-02, -2.20864802e-06,  8.62637077e-05],
       [-2.20864802e-06,  9.82525119e-05, -3.89511839e-05],
       [ 8.62637077e-05, -3.89511839e-05,  1.53545511e-02]])

In [50]:
min_index = np.argmin(default_wall[:, 1, 1])
print("default min y cov\n")
default_min_y_cov = default_wall[min_index]
print(default_min_y_cov)

max_index = np.argmax(default_wall[:, 1, 1])
print("default max y cov\n")
default_max_y_cov = default_wall[max_index]
print(default_max_y_cov)

print("default mean y cov")
corrected_wall.mean(axis=0)

default min y cov

[[ 0.00736651  0.00063723 -0.00011427]
 [ 0.00063723  0.00011476 -0.00041708]
 [-0.00011427 -0.00041708  0.00515427]]
default max y cov

[[0.01504897 0.0022557  0.00171556]
 [0.0022557  0.00042892 0.00022697]
 [0.00171556 0.00022697 0.00638195]]
default mean y cov


array([[ 2.01425446e-02, -2.20864802e-06,  8.62637077e-05],
       [-2.20864802e-06,  9.82525119e-05, -3.89511839e-05],
       [ 8.62637077e-05, -3.89511839e-05,  1.53545511e-02]])

In [51]:
min_index = np.argmin(corrected_wall[:, 1, 1])
print("corrected min y cov\n")
corrected_min_y_cov = corrected_wall[min_index]
print(corrected_min_y_cov)

max_index = np.argmax(corrected_wall[:, 1, 1])
print("corrected max y cov\n")
corrected_max_y_cov = corrected_wall[max_index]
print(corrected_max_y_cov)

print("corrected mean y cov")
corrected_wall.mean(axis=0)

corrected min y cov

[[ 1.27185872e-02  1.78528971e-05 -2.90005282e-03]
 [ 1.78528971e-05  6.12400254e-05 -6.12546614e-07]
 [-2.90005282e-03 -6.12546614e-07  1.78487059e-02]]
corrected max y cov

[[ 1.67850982e-02 -1.97004221e-04 -3.45942960e-03]
 [-1.97004221e-04  1.59573581e-04  1.45979893e-05]
 [-3.45942960e-03  1.45979893e-05  1.47080077e-02]]
corrected mean y cov


array([[ 2.01425446e-02, -2.20864802e-06,  8.62637077e-05],
       [-2.20864802e-06,  9.82525119e-05, -3.89511839e-05],
       [ 8.62637077e-05, -3.89511839e-05,  1.53545511e-02]])

In [ ]:
from plotly.subplots import make_subplots

axes = ['X', 'Y', 'Z']
diag_idx = [(0, 0), (1, 1), (2, 2)]
colors = {'default': 'royalblue', 'corrected': 'salmon'}

fig_cov_diag = make_subplots(rows=1, cols=3, subplot_titles=axes)

for i, (ax_label, (r, c)) in enumerate(zip(axes, diag_idx), start=1):
    y_def = default_wall[:, r, c]
    y_cor = corrected_wall[:, r, c]

    overall_min = float(min(y_def.min(), y_cor.min()))
    overall_max = float(max(y_def.max(), y_cor.max()))
    rng = overall_max - overall_min
    pad = max(rng * 0.1, 1e-8)

    fig_cov_diag.add_trace(
        go.Box(y=y_def, name='default', marker_color=colors['default'],
               boxmean=True, legendgroup='default', showlegend=(i == 1)),
        row=1, col=i
    )
    fig_cov_diag.add_trace(
        go.Box(y=y_cor, name='corrected', marker_color=colors['corrected'],
               boxmean=True, legendgroup='corrected', showlegend=(i == 1)),
        row=1, col=i
    )

    fig_cov_diag.update_yaxes(range=[overall_min - pad, overall_max + pad], row=1, col=i)
    fig_cov_diag.update_xaxes(title_text=ax_label, row=1, col=i)

fig_cov_diag.update_layout(
    title='Diagonal covariance comparison (default vs corrected)',
    boxmode='group',
    template='plotly_white',
    margin=dict(l=40, r=20, t=60, b=40)
)

fig_cov_diag.show()


In [53]:
mean_cov_default = np.array([[0.01509147, 0.00216262, 0.00066579],
                            [0.00216262, 0.00053155, 0.00036626],
                            [0.00066579, 0.00036626, 0.01609784]])

In [54]:
mean_cov_corrected = np.array([[ 2.0666488e-02, -6.0715567e-05,  3.3077397e-04],
                            [-6.0715567e-05,  4.3647480e-03,  8.5450482e-04],
                            [ 3.3077397e-04,  8.5450482e-04,  1.8785335e-02]])


In [55]:
def mesh_from_cov(cov, center=None, n_pts=40, color='royalblue', name='ellipsoid', opacity=0.6):
    if center is None:
        center = np.zeros(3)
    cov = 0.5 * (cov + cov.T)
    evals, evecs = np.linalg.eigh(cov)
    evals = np.clip(evals, 1e-12, None)
    radii = np.sqrt(evals)

    u = np.linspace(0, 2*np.pi, n_pts)
    v = np.linspace(0, np.pi, n_pts)
    u, v = np.meshgrid(u, v)

    x = np.cos(u) * np.sin(v)
    y = np.sin(u) * np.sin(v)
    z = np.cos(v)
    xyz = np.stack((x.ravel(), y.ravel(), z.ravel()), axis=0)  # (3, N)

    transform = (evecs @ np.diag(radii)) @ xyz
    X = (transform[0] + center[0]).reshape(u.shape)
    Y = (transform[1] + center[1]).reshape(u.shape)
    Z = (transform[2] + center[2]).reshape(u.shape)

    # build triangles for a Mesh3d from grid indices
    n_u, n_v = u.shape
    i = []
    j = []
    k = []
    for ii in range(n_u - 1):
        for jj in range(n_v - 1):
            a = ii * n_v + jj
            b = a + 1
            c = (ii + 1) * n_v + jj
            d = c + 1
            # two triangles per quad
            i += [a, b]
            j += [b, d]
            k += [c, c]

    return go.Mesh3d(
        x=X.ravel(), y=Y.ravel(), z=Z.ravel(),
        i=i, j=j, k=k,
        color=color, opacity=opacity,
        name=name, flatshading=True, showscale=False
    )

# choose centers (optional) to separate visuals if needed
center_default = np.array([-0.0, 0.0, 0.0])
center_corrected = np.array([ 0.0, 0.0, 0.0])

m1 = mesh_from_cov(mean_cov_default, center=center_default, n_pts=40, color='royalblue', name='default mean', opacity=0.5)
m2 = mesh_from_cov(mean_cov_corrected, center=center_corrected, n_pts=40, color='salmon', name='corrected mean', opacity=0.5)

fig = go.Figure(data=[m1, m2])
fig.update_layout(
    title='Interactive ellipsoids (Plotly)',
    legend=dict(itemsizing='constant'),
    scene=dict(
        xaxis_title='X', yaxis_title='Y', zaxis_title='Z',
        aspectmode='cube'  # equal aspect
    ),
    margin=dict(l=0, r=0, b=0, t=40)
)

fig.show()
